import {PAGE_START} from "./PAGE_START.js";
import {PAGE_CUSTOMER_LIST} from "./PAGE_CUSTOMER_LIST.js";
import {PAGE_SETTING_PRIVATE_KEY} from "./PAGE_SETTING_PRIVATE_KEY.js";
import {PAGE_EQUIPMENT_LIST} from "./PAGE_EQUIPMENT_LIST.js";
import {PAGE_TASK_LIST} from "./PAGE_TASK_LIST.js";
import {PAGE_LOGIN} from "./PAGE_LOGIN.js";
import {PAGE_CUSTOMER_DESCRIPTION} from "./PAGE_CUSTOMER_DESCRIPTION.js";
import {PAGE_EQUIPMENT_DESCRIPTION} from "./PAGE_EQUIPMENT_DESCRIPTION.js";

export function register_all_page() {
    PAGE_SETTING_PRIVATE_KEY();
    PAGE_START();
    PAGE_CUSTOMER_LIST();
    PAGE_EQUIPMENT_LIST();
    PAGE_TASK_LIST();
    PAGE_LOGIN();
    PAGE_CUSTOMER_DESCRIPTION();
    PAGE_EQUIPMENT_DESCRIPTION();
}