export function create_database() {
	alasql("CREATE TABLE IF NOT EXISTS `tab_customer` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`title` char NOT NULL,\n"
        + "\t`town` char(50) NOT NULL,\n"
        + "\t`address` char NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");"
        + "CREATE TABLE IF NOT EXISTS `tab_contract` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_customer` char(36) NOT NULL,\n"
        + "\t`num` char NOT NULL,\n"
        + "\t`date_begin` DATE NOT NULL,\n"
        + "\t`date_end` DATE NOT NULL,\n"
        + "\t`description` TEXT NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");"
        + "CREATE TABLE IF NOT EXISTS `tab_equipment` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_category` char(36) NOT NULL,\n"
        + "\t`GUID_title` char(36) NOT NULL,\n"
        + "\t`model` char NOT NULL,\n"
        + "\t`service_time` FLOAT NOT NULL,\n"
        + "\t`ID_frequency` int NOT NULL,\n"
        + "\t`GUID_manufacturer` char(36) NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_equipment_category` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`sort_id` int NOT NULL,\n"
        + "\t`title` char(50) NOT NULL,\n"
        + "\t`ID_division` char(20) NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_equipment_node` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_group` char(36) NOT NULL,\n"
        + "\t`title` char NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_equipment_node_group` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`title` char NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_equipment_node_join` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_equipment` char(36) NOT NULL,\n"
        + "\t`GUID_node` char(36) NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_service_job` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_equipment_node` char(36) NOT NULL,\n"
        + "\t`ID_frequency` int NOT NULL,\n"
        + "\t`service_time` FLOAT NOT NULL,\n"
        + "\t`service_job` TEXT NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_user` (\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`ID_division` char(20) NOT NULL,\n"
        + "\t`private_key` char(255) NOT NULL,\n"
        + "\t`uname` char(50) NOT NULL,\n"
        + "\t`mail` char(50) NOT NULL,\n"
        + "\t`level` int NOT NULL,\n"
        + "\t`is_enable` int NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_division` (\n"
        + "\t`ID` char(20) NOT NULL,\n"
        + "\t`title` char NOT NULL,\n"
        + "\tPRIMARY KEY (`ID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_contract_division` (\n"
        + "\t`ID_division` char(20) NOT NULL,\n"
        + "\t`GUID_contract` char(36) NOT NULL\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_equipment_title` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`title` char NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_customer_equipment` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_customer` char(36) NOT NULL,\n"
        + "\t`GUID_equipment` char(36) NOT NULL,\n"
        + "\t`serial` char NOT NULL,\n"
        + "\t`invent` char NOT NULL,\n"
        + "\t`date_create` char(20) NOT NULL,\n"
        + "\t`date_input` char(20) NOT NULL,\n"
        + "\t`destination` char NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_contract_equipment` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_customer_equipment` char(36) NOT NULL,\n"
        + "\t`GUID_contract` char(36) NOT NULL,\n"
        + "\t`ID_frequency` int NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_service_frequency` (\n"
        + "\t`ID` int NOT NULL,\n"
        + "\t`frequency` int NOT NULL,\n"
        + "\t`title` char(20) NOT NULL,\n"
        + "\tPRIMARY KEY (`ID`)\n"
        + ");\n"
        + "CREATE TABLE IF NOT EXISTS `tab_manufacturer` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`title` char(20) NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "CREATE TABLE IF NOT EXISTS `tab_encryption` (\n"
        + "\t`encryption_seed` char(255) NOT NULL,\n"
        + "\t`GUID_user` char(36) NOT NULL,\n"
        + "\t`validity` DATETIME NOT NULL,\n"
        + "\tPRIMARY KEY (`encryption_seed`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_task` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`task_type` char(10) NOT NULL,\n"
        + "\t`task_state` char(10) NOT NULL,\n"
        + "\t`GUID_customer` char(36) NOT NULL,\n"
        + "\t`GUID_contract` char(36) NOT NULL,\n"
        + "\t`date_create` DATETIME NOT NULL,\n"
        + "\t`date_begin` DATETIME NOT NULL,\n"
        + "\t`date_deadline` DATETIME NOT NULL,\n"
        + "\t`time_duration` FLOAT NOT NULL,\n"
        + "\t`description` TEXT NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_task_type` (\n"
        + "\t`ID` char(10) NOT NULL UNIQUE,\n"
        + "\t`title` char NOT NULL\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_task_equipment` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_customer_equipment` char(36) NOT NULL,\n"
        + "\t`GUID_task` char(36) NOT NULL,\n"
        + "\t`description` TEXT NOT NULL,\n"
        + "\t`is_finish` bool NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_additional_job` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_task_equipment` char(36) NOT NULL,\n"
        + "\t`caption` TEXT NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_additional_job_act` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_additional_job` char(36) NOT NULL,\n"
        + "\t`GUID_employee` char(36) NOT NULL,\n"
        + "\t`time_begin` DATETIME NOT NULL,\n"
        + "\t`time_duration` FLOAT NOT NULL,\n"
        + "\t`is_finish` bool NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_service_job_act` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_service_job` char(36) NOT NULL,\n"
        + "\t`GUID_employee` char(36) NOT NULL,\n"
        + "\t`GUID_task_equipment` char(36) NOT NULL,\n"
        + "\t`time_begin` DATETIME NOT NULL,\n"
        + "\t`time_duration` FLOAT NOT NULL,\n"
        + "\t`is_finish` bool NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_equipment_failure_target` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`time_insert` DATETIME NOT NULL,\n"
        + "\t`GUID_task_equipment` char(36) NOT NULL,\n"
        + "\t`GUID_employee` char(36) NOT NULL,\n"
        + "\t`description` TEXT NOT NULL,\n"
        + "\t`is_cheked` bool NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_equipment_failure_sign` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_employee` char(36) NOT NULL,\n"
        + "\t`GUID_equipment_node` char(36) NOT NULL,\n"
        + "\t`GUID_task_equipment` char(36) NOT NULL,\n"
        + "\t`description` TEXT NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_equipment_failure_target_comment` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_employee` char(36) NOT NULL,\n"
        + "\t`GUID_target` char(36) NOT NULL,\n"
        + "\t`description` TEXT NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_task_employee` (\n"
        + "\t`is_delete` int NOT NULL,\n"
        + "\t`time_update` DATETIME NOT NULL,\n"
        + "\t`GUID` char(36) NOT NULL,\n"
        + "\t`GUID_user` char(36) NOT NULL,\n"
        + "\t`GUID_task` char(36) NOT NULL,\n"
        + "\tPRIMARY KEY (`GUID`)\n"
        + ");\n"
        + "\n"
        + "CREATE TABLE IF NOT EXISTS `tab_task_state` (\n"
        + "\t`ID` char(10) NOT NULL,\n"
        + "\t`title` char NOT NULL\n"
        + ");"
        + "CREATE TABLE IF NOT EXISTS `server_transact` (\n"
        + "  `ID` int(11) NOT NULL,\n"
        + "  `GUID` char(36) NOT NULL,\n"
        + "  `time_update` datetime NOT NULL,\n"
        + "  `table_name` char(25) NOT NULL,\n"
        + "  `query_type` char(25) NOT NULL,\n"
        + "  `GUID_record` char(36) NOT NULL,\n"
        + "  `GUID_user` char(36) NOT NULL\n"
        + ");"
        + "CREATE TABLE IF NOT EXISTS `client_transact` (\n"
        + "  `ID` int(11) NOT NULL,\n"
        + "  `GUID` char(36) NOT NULL,\n"
        + "  `table_name` char(25) NOT NULL,\n"
        + "  `query_type` char(25) NOT NULL,\n"
        + "  `GUID_record` char(36) NOT NULL\n"
        + ");",
	);
}
